// `define CLK_32M
// `define COUNTER_NUM   0
// `define COUNTER_NUM   1
// `define COUNTER_NUM   2
// `define COUNTER_NUM   3

// `define TESTCASE_C0_WAVEFORM_0
// `define TESTCASE_C0_WAVEFORM_1
 // `define TESTCASE_C0_WAVEFORM_2
// `define TESTCASE_C0_WAVEFORM_3

// `define TESTCASE_C0_CAPTURE_0
// `define TESTCASE_C0_CAPTURE_1
// `define TESTCASE_C0_CAPTURE_2

 // `define TESTCASE_C0_SHIFTIN_0
 // `define TESTCASE_C0_SHIFTIN_1
 // `define TESTCASE_C0_SHIFTIN_2

// `define TESTCASE_C0_SHIFTOUT_0
// `define TESTCASE_C0_SHIFTOUT_1
// `define TESTCASE_C0_SHIFTOUT_2

// `define TESTCASE_C0_SW_COUNTMODE_0
// `define TESTCASE_C0_SW_COUNTMODE_1
// `define TESTCASE_C0_SW_COUNTMODE_2


// `define TESTCASE_C0_SW_SHIFTMODE_0
// `define TESTCASE_C0_SW_SHIFTMODE_1
// `define TESTCASE_C0_SW_SHIFTMODE_2

// `define CAPTURE_DATA_CASECADE

 `define TESTCASE_ALL_SHIFTMODE_0
// `define TESTCASE_ALL_SHIFTMODE_1

// `define TESTCASE_ALL_COUNTERMODE_0
// `define TESTCASE_ALL_COUNTERMODE_1
// `define TESTCASE_ALL_COUNTERMODE_2
//`define TESTCASE_ALL_COUNTERMODE_3

//
//
// `define TESTCASE_C1_WAVEFORM_0
// `define TESTCASE_C1_WAVEFORM_1
// `define TESTCASE_C1_WAVEFORM_2
// `define TESTCASE_C1_WAVEFORM_3
// 
// 
// `define TESTCASE_C2_WAVEFORM_0
// `define TESTCASE_C2_WAVEFORM_1
// `define TESTCASE_C2_WAVEFORM_2
// `define TESTCASE_C2_WAVEFORM_3
// 
// `define TESTCASE_C3_WAVEFORM_0
// `define TESTCASE_C3_WAVEFORM_1
// `define TESTCASE_C3_WAVEFORM_2
// `define TESTCASE_C3_WAVEFORM_3
