`define CLK_32M
`define COUNTER_NUM   0
// `define COUNTER_NUM   1
// `define COUNTER_NUM   2
// `define COUNTER_NUM   3

// `define SIM_FINISH_MS 10
// `define SIM_FINISH_MS 20
// `define SIM_FINISH_MS 50
`define SIM_FINISH_MS 200
`define APB_BUS_MONITOR

// `define CAPTURE_DATA_IN
// `define SHIFT_DATA_IN

// `define TESTCASE_C0_WAVEFORM_0
// `define TESTCASE_C0_WAVEFORM_1
 // `define TESTCASE_C0_WAVEFORM_2
// `define TESTCASE_C0_WAVEFORM_3

// `define TESTCASE_C0_CAPTURE_0
// `define TESTCASE_C0_CAPTURE_1
// `define TESTCASE_C0_CAPTURE_2

 // `define TESTCASE_C0_SHIFTIN_0
 // `define TESTCASE_C0_SHIFTIN_1
 // `define TESTCASE_C0_SHIFTIN_2

// `define TESTCASE_C0_SHIFTOUT_0
// `define TESTCASE_C0_SHIFTOUT_1
// `define TESTCASE_C0_SHIFTOUT_2

// `define TESTCASE_C0_SW_COUNTMODE_0
// `define TESTCASE_C0_SW_COUNTMODE_1
// `define TESTCASE_C0_SW_COUNTMODE_2


// `define TESTCASE_C0_SW_SHIFTMODE_0
// `define TESTCASE_C0_SW_SHIFTMODE_1
// `define TESTCASE_C0_SW_SHIFTMODE_2

// `define CAPTURE_DATA_CASECADE

// `define TESTCASE_ALL_SHIFTMODE_0
// `define TESTCASE_ALL_SHIFTMODE_1

//`define TESTCASE_ALL_COUNTERMODE_0
//`define TESTCASE_ALL_COUNTERMODE_1
//`define TESTCASE_ALL_COUNTERMODE_2
`define TESTCASE_ALL_COUNTERMODE_3

//`define TESTCASE_ALL_COUNTERMODE_4 //single trigger.
//`define TESTCASE_ALL_COUNTERMODE_5 //global trigger.
//`define TESTCASE_ALL_COUNTERMODE_6 // start 、stop


