
// `define TESTCASE_C0_WAVEFORM_0
// `define TESTCASE_C0_WAVEFORM_1
 // `define TESTCASE_C0_WAVEFORM_2
//`define TESTCASE_C0_WAVEFORM_3

// `define TESTCASE_C0_CAPTURE_0
// `define TESTCASE_C0_CAPTURE_1
// `define TESTCASE_C0_CAPTURE_2

 // `define TESTCASE_C0_SHIFTIN_0
 // `define TESTCASE_C0_SHIFTIN_1
 // `define TESTCASE_C0_SHIFTIN_2

// `define TESTCASE_C0_SHIFTOUT_0
// `define TESTCASE_C0_SHIFTOUT_1
// `define TESTCASE_C0_SHIFTOUT_2

// `define TESTCASE_C0_SW_COUNTMODE_0


`define TESTCASE_C0_SW_SHIFTMODE_0



//
//
// `define TESTCASE_C1_WAVEFORM_0
// `define TESTCASE_C1_WAVEFORM_1
// `define TESTCASE_C1_WAVEFORM_2
// `define TESTCASE_C1_WAVEFORM_3
// 
// 
// `define TESTCASE_C2_WAVEFORM_0
// `define TESTCASE_C2_WAVEFORM_1
// `define TESTCASE_C2_WAVEFORM_2
// `define TESTCASE_C2_WAVEFORM_3
// 
// `define TESTCASE_C3_WAVEFORM_0
// `define TESTCASE_C3_WAVEFORM_1
// `define TESTCASE_C3_WAVEFORM_2
// `define TESTCASE_C3_WAVEFORM_3
